name: Deploy StockTrack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar dependencias del backend
        run: |
          cd /home/ubuntu/actions-runner/_work/proyecto_final_idt/proyecto_final_idt/server
          npm install
          npx prisma generate
          npx prisma migrate deploy
          pm2 restart stocktrack-api || pm2 start src/server.js --name stocktrack-api
          pm2 save

      - name: Compilar frontend
        run: |
          cd /home/ubuntu/actions-runner/_work/proyecto_final_idt/proyecto_final_idt/cliente
          npm install
          npm run build

      - name: Publicar frontend en Nginx
        run: |
          sudo mkdir -p /var/www/stocktrack
          sudo rm -rf /var/www/stocktrack/*
          sudo cp -r /home/ubuntu/actions-runner/_work/proyecto_final_idt/proyecto_final_idt/cliente/dist/* /var/www/stocktrack/
          sudo systemctl restart nginx